<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-12-19 21:16

$extensionPath = t3lib_extMgm::extPath('tce_tutorial');
return array(
	'tx_tcetutorial_tcarelationservicetest' => $extensionPath . 'tests/tx_tcetutorial_TcaRelationserviceTest.php',
);
?>